# status-bar
set-option -g status-interval 1
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=#0B0E14,fg=#475266"

set -g window-status-separator " • "
set -g window-status-format ' [#I] #{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}} #[default] '
set -g window-status-current-format '#[bg=#{?client_prefix,#95E6CB,default},fg=#{?client_prefix,#0B0E14,#BFBDB6}] [#I] #{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}} #{?window_zoomed_flag,󰊓,}#[default] '

# 左右のstatusは非表示
set -g status-left ""
set -g status-right ""

# 非アクティブなpane
set -g window-style 'fg=#6b7089,bg=#0f1117'
# アクティブなpane
set -g window-active-style 'fg=#c6c8d1,bg=#161821'
