# 秘伝のvimrc準拠
set-window-option -g mode-keys vi

# / でincremental search（下方向）
bind -T copy-mode-vi / command-prompt -i -p "(search down)" "send -X search-forward-incremental \"%%%\""
# ? でincremental search（上方向）
bind -T copy-mode-vi ? command-prompt -i -p "(search up)" "send -X search-backward-incremental \"%%%\""

# 検索
bind -T copy-mode-vi n send -X search-again
bind -T copy-mode-vi N send -X search-reverse

# vimと同じバインドで選択
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle

# yank時に copy-mode を抜けないように
bind -T copy-mode-vi y send -X copy-selection

# Ctrl + j, k で段落移動
bind -T copy-mode-vi C-j send -X next-paragraph
bind -T copy-mode-vi C-k send -X previous-paragraph
# Ctrl + h, l で単語移動
bind -T copy-mode-vi C-h send -X previous-word
bind -T copy-mode-vi C-l send -X next-word

# Tabでいっぱい移動
bind -T copy-mode-vi Tab send -X -N 5 cursor-down
bind -T copy-mode-vi BTab send -X -N 5 cursor-up

# Escを連打すればいい感じに
bind -T copy-mode-vi Escape if-shell -F "#{selection_present}" "send -X clear-selection" "send -X cancel"
