# Prefix Ctrl+Q
set -g prefix C-q
unbind C-b

# 256色モードを有効にする
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# windowのインデックスを1から始める
set -g base-index 1
set-option -g renumber-windows on
setw -g pane-base-index 1

# マウス操作を有効にする
set-option -g mouse on

# visual notification
set-window-option -g monitor-activity on
set -g visual-activity on
