# key bindings
set -s escape-time 0

# prefix+r で設定のリロード
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

bind c new-window -c '#{pane_current_path}'

# ポップアップ Ctrl+Q x 2
bind C-q display-popup -d '#{pane_current_path}'
bind Q display-popup -d '#{pane_current_path}' -E
bind C-t popup -xC -yC -w70% -h90% -d '#{pane_current_path}' -E 'tig'

# Ctrl + 1~9
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

bind-key -n M-h previous-window
bind-key -n M-l next-window

# pane分割
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Shift+xで即kill
bind X kill-pane

# pane移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# paneリサイズ
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# window移動
bind n next-window
bind N previous-window

bind -n M-w kill-window
