# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

tpm_version="3.1.0"
tpm_dir="${HOME}/.config/tmux/plugins/tpm"
tpm_repo_url="https://github.com/tmux-plugins/tpm.git"
if "test ! -d ${tpm_dir}" \
     "run 'git clone --depth=1 -b v${tpm_version} ${tpm_repo_url} ${tpm_dir} && ${tpm_dir}/bindings/install_plugins'"

run "${tpm_dir}/tpm"
